# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='vectiles.proto',
  package='de.pwrk.vectiles',
  serialized_pb='\n\x0evectiles.proto\x12\x10\x64\x65.pwrk.vectiles\"3\n\x07Vectile\x12(\n\x05polys\x18\x01 \x03(\x0b\x32\x19.de.pwrk.vectiles.Polygon\"P\n\x07Polygon\x12#\n\x04tags\x18\x01 \x03(\x0b\x32\x15.de.pwrk.vectiles.Tag\x12\x0f\n\x07\x64\x65lta_x\x18\x02 \x03(\x11\x12\x0f\n\x07\x64\x65lta_y\x18\x03 \x03(\x11\"\x1b\n\x03Tag\x12\t\n\x01k\x18\x01 \x02(\t\x12\t\n\x01v\x18\x02 \x02(\t')




_VECTILE = descriptor.Descriptor(
  name='Vectile',
  full_name='de.pwrk.vectiles.Vectile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='polys', full_name='de.pwrk.vectiles.Vectile.polys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=87,
)


_POLYGON = descriptor.Descriptor(
  name='Polygon',
  full_name='de.pwrk.vectiles.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tags', full_name='de.pwrk.vectiles.Polygon.tags', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delta_x', full_name='de.pwrk.vectiles.Polygon.delta_x', index=1,
      number=2, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delta_y', full_name='de.pwrk.vectiles.Polygon.delta_y', index=2,
      number=3, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=89,
  serialized_end=169,
)


_TAG = descriptor.Descriptor(
  name='Tag',
  full_name='de.pwrk.vectiles.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='k', full_name='de.pwrk.vectiles.Tag.k', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='v', full_name='de.pwrk.vectiles.Tag.v', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=171,
  serialized_end=198,
)

_VECTILE.fields_by_name['polys'].message_type = _POLYGON
_POLYGON.fields_by_name['tags'].message_type = _TAG
DESCRIPTOR.message_types_by_name['Vectile'] = _VECTILE
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['Tag'] = _TAG

class Vectile(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VECTILE
  
  # @@protoc_insertion_point(class_scope:de.pwrk.vectiles.Vectile)

class Polygon(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POLYGON
  
  # @@protoc_insertion_point(class_scope:de.pwrk.vectiles.Polygon)

class Tag(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TAG
  
  # @@protoc_insertion_point(class_scope:de.pwrk.vectiles.Tag)

# @@protoc_insertion_point(module_scope)
